# load libraries
library(ergm)
library(sna)
library(Bergm)
library(stringr)
library(LaplacesDemon)
library(mvtnorm)
library(SparseM)
library(tictoc)
library(cowplot)
library(Rglpk)
library(Matrix)

setwd("~/Documents/Harvard/Senior Year/Thesis/project/code")
#setwd("/home/rstudio/dp-ergm-thesis/code")
